"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[cmd_duration]
min_time = 900

[directory]
home_symbol = "ğŸ "

[status]
disabled = false
pipestatus = true
map_symbol = true

[sudo]
enabled = true


